export const selectCars = (state) => state.cars.items;
export const selectSelectedCar = (state) => state.cars.selectedCar;
export const selectBrands = (state) => state.cars.brands;
export const selectPage = (state) => state.cars.page;
export const selectHasMore = (state) => state.cars.hasMore;
export const selectFilters = (state) => state.cars.filters;
export const selectLoading = (state) => state.cars.loading;
export const selectError = (state) => state.cars.error;
export const selectFavorites = (state) => state.cars.favorites;
